export { default as home } from './home.vue'
export { default as logout } from './logout.vue'
export { default as star } from './star.vue'
export { default as fork } from './fork.vue'
export { default as triangle } from './triangle.vue'
